version: '3.8'

services:
  checklytool:
    build: .
    container_name: checklytool_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: checklytool_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - checklytool
    networks:
      - web

networks:
  web:
    driver: bridge