version: '3.8'

services:
  checklytool:
    build: .
    container_name: checklytool_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_AUDIENCE_ID=${RESEND_AUDIENCE_ID}
    env_file:
      - .env
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: checklytool_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - checklytool
    networks:
      - web

  webhook:
    image: node:18-alpine
    container_name: checklytool_webhook
    restart: always
    # Убираем внешний порт - доступ только через nginx
    expose:
      - "${WEBHOOK_PORT:-9000}"
    volumes:
      - ./webhook-server.mjs:/app/webhook-server.mjs
      - ./deploy.sh:/app/deploy.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app/project
    working_dir: /app
    command: node webhook-server.mjs
    environment:
      - NODE_ENV=production
      - WEBHOOK_PORT=${WEBHOOK_PORT:-9000}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    driver: bridge